### ISSUE TITLE
Why was pluto chosen for the name?

### ISSUE THREAD

**Issue by markfirmware** [ZystemOS/pluto#236]

**Comment by SamTebbs33** [comment]
I don't remember there being a specific reason but @DrDeano may be able to enlighten us. We recently decided to name the OS itself (that the kernel is part of) from something to do with the solar system (the kernel is a small part of an OS, just like Pluto is a small part of the solar system) but we couldn't find any good available names so (probably temporarily) went with Zystem (Solar system -> System -> Zystem because of the Z in Zig).

**Comment by DrDeano** [comment]
There isn't really a specific reason why we chose the name. But as always, we leave it to the users imagination to come up with a good back story. We do plan for the whole system to be solar system/space themed.

**Comment by markfirmware** [comment]
I see. Thanks!
